/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

// generate enum based on strings instead of numbers
// (see https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/)
export enum status {
    placed = <any>"placed",
    approved = <any>"approved",
    delivered = <any>"delivered",
}

export enum status {
    available = <any>"available",
    pending = <any>"pending",
    sold = <any>"sold",
}


