/**
 * This file is generated by the SwaggerTSGenerator.
 * Do not edit.
*/
/* tslint:disable */

// generate enum based on strings instead of numbers
// (see https://blog.rsuter.com/how-to-implement-an-enum-with-string-values-in-typescript/)
export enum status {
    placed = <any>"placed",
    approved = <any>"approved",
    delivered = <any>"delivered",
}

export enum status {
    available = <any>"available",
    pending = <any>"pending",
    sold = <any>"sold",
}

export enum name {
    ErreurDeSaisie = <any>"ErreurDeSaisie",
    ClientIndisponible = <any>"ClientIndisponible",
    ExpertIndisponible = <any>"ExpertIndisponible",
    TiersIndisponible = <any>"TiersIndisponible",
    DossierIncomplet = <any>"DossierIncomplet",
    Autre = <any>"Autre",
}

export enum label {
    Erreur de saisie = <any>"Erreur de saisie",
    Client indisponible = <any>"Client indisponible",
    Expert indisponible = <any>"Expert indisponible",
    Tiers indisponible = <any>"Tiers indisponible",
    Dossier incomplet / En attente retour client = <any>"Dossier incomplet / En attente retour client",
    Autre = <any>"Autre",
}


